import torch
from diffusers import StableDiffusionInpaintPipeline
from peft import PeftModel
from PIL import Image
import numpy as np

device = "cuda"

base_model = "runwayml/stable-diffusion-inpainting"
pipe = StableDiffusionInpaintPipeline.from_pretrained(
    base_model,
    torch_dtype=torch.float16,
    safety_checker=None
).to(device)

# Pack UNet with LoRA
from peft import PeftModel
pipe.unet = PeftModel.from_pretrained(pipe.unet, "/Users/rayno/Workspace/ML/BreastCancer/Train/RecFinal/best_lora")
pipe.unet.to(device)

# get noisy image with mask
def gray_to_rgb(img: Image.Image) -> Image.Image:
    if img.mode != "L":
        img = img.convert("L")
    arr = np.array(img)
    rgb_arr = np.stack([arr, arr, arr], axis=-1)
    return Image.fromarray(rgb_arr.astype(np.uint8), mode="RGB")

flawed = Image.open("imgText027.png").convert("L")
rgb_flawed = gray_to_rgb(flawed)

# manual mask
mask = Image.open("/Users/rayno/Workspace/ML/BreastCancer/Test/adjacentMask027.png").convert("L")

prompt = "Ultrasound, breast, benign lesion, grayscale"  # prompt generated by GPT

image = pipe(
    prompt=prompt,
    image=rgb_flawed,
    mask_image=mask,
    guidance_scale=7.5,
    num_inference_steps=50
).images[0]

image.save("inpaint_result027_19.png")
